### ISSUE TITLE
Add files to .GITIGNORE

### ISSUE THREAD

**Issue by danarth** [ASE-ESRS/Group-Project#15]
The the .GITIGNORE, can someone add `.idea`, `.iml` and `build` please?

**Comment by LoicVerrall** [comment]
Do we still need to do this?

**Comment by danarth** [comment]
I think I might have done it. I'll check now!

**Comment by LoicVerrall** [comment]
Yeah, looks like you've made some more specific ignores (e.g. .idea/workspace)
