### ISSUE TITLE
Document server-side decisions

### ISSUE THREAD

**Issue by LoicVerrall** [ASE-ESRS/Group-Project#24]
- Why did we choose AWS, and, more specifically Lambda, over Google Cloud, elastic beanstalk, etc.
- Why did we choose Node.js as the development language here.

- Why did we choose a NoSQL approach over a traditional relational approach?
- Why did we choose writing to a database as opposed to writing individual files on a server?
- Why did we choose DynamoDB?

**Comment by danarth** [comment]
Maybe some more things to think about (if you like them please update the issue):
- Why did we choose a NoSQL approach over a traditional relational approach?
- Why did we choose writing to a database as opposed to writing individual files on a server?
- Why did we choose DynamoDB?

**Comment by LoicVerrall** [comment]
I have updated the server-side documentation to include these changes
