### ISSUE TITLE
Update Project Plan

### ISSUE THREAD

**Issue by LoicVerrall** [ASE-ESRS/Group-Project#34]
Include information about how we are 'testing' out **code quality** throughout the development by using testing (how? when? how much? automated?) and code reviews (how? when? who? here we should talk about us all forking the main repo and using pull requests to ask for a code review).

Also, on the topic of **code reviews** I think it would be great to reference the Google and Facebook papers here, as they have the same policy as us: code changes to the master branch _must_ undergo a code review by at least one other member of our team.

Declare our engineering methodology as **Agile** and explain how we use the **Issues** section on GitHub to track our to-do list and **Slack** for all non-person-to-person communication. Can also discuss how we have different channels to group together related messages.

**Comment by Tang-1996** [comment]
Added three new section, testing, code review and methodology. Please edit as needed
