### ISSUE TITLE
Can't open Android Studio project

### ISSUE THREAD

**Issue by danarth** [ASE-ESRS/Group-Project#7]
I am not sure if it's just me but when I fork the repo I can't open the Android Studio project.

Could someone else give this a go and see if it's just me being stupid?

**Comment by LoicVerrall** [comment]
My project window just doesn't show any files. Is that the same problem you're having?

**Comment by danarth** [comment]
Yeah exactly the same problem here, maybe a `.iml` file wasn't added to the commit that is stopping Android Studio from knowing the project file structure?

**Comment by LoicVerrall** [comment]
But Alex reuploaded a whole new project (with that file and everything else). We only didn't include that in the original project (now deleted).

**Comment by LoicVerrall** [comment]
<img width="984" alt="screen shot 2017-10-13 at 01 01 14" src="https://user-images.githubusercontent.com/17081120/31524516-0714af9e-afb2-11e7-8668-a88232df68b4.png">
Actually look at this, the only files in the repo are three Java classes... no wonder AS doesn't recognise it as a project...

**Comment by danarth** [comment]
Yeah I just noticed that! No XML files anywhere... Maybe it's worth creating a new project, so strange. Also, for future reference, from [what I've read online](https://stackoverflow.com/a/30737309/4934818) it's good practice to add `.idea` and `*.iml` to the `.gitignore` file.
